version: '3.3'
services:

  node-exporter:
    image: prom/node-exporter:latest
    user: root
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points="^/(sys|proc|dev|host|etc)($$|/)"'
    networks:
      mgmt_net:
        aliases:
          - node-exporter-dmz

  mongodb-exporter:
    image: ${DOCKER_USERNAME}/mongodb_exporter:${MONGODB_EXPORTER_VERSION}
    command: ["-mongodb.uri", "post_db-back"]
    networks:
      back_net:
      mgmt_net:
        aliases:
          - mongodb-exporter-dmz

  blackbox-exporter:
    image: ${DOCKER_USERNAME}/blackbox_exporter:${BLACKBOX_EXPORTER_VERSION}
    command:
      - '--config.file=/etc/blackbox_exporter/config.yml'
      - '--web.listen-address=blackbox-exporter-dmz:9115'
    networks:
      front_net:
      mgmt_net:
        aliases:
          - blackbox-exporter-dmz

  cadvisor:
    image: google/cadvisor:v0.29.0
    volumes:
      - '/:/rootfs:ro'
      - '/var/run:/var/run:rw'
      - '/sys:/sys:ro'
      - '/var/lib/docker/:/var/lib/docker:ro'
    ports:
      - '8080:8080'
    networks:
      mgmt_net:
        aliases:
          - cadvisor-dmz

  grafana:
    image: grafana/grafana:5.0.0-beta4
    volumes:
      - grafana_data:/var/lib/grafana
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=secret
    depends_on:
      - prometheus
    ports:
      - 3000:3000
    networks:
      mgmt_net:
        aliases:
          - grafana-dmz

  prometheus:
    image: ${DOCKER_USERNAME}/prometheus:${PROMETHEUS_VERSION}
    ports:
      - '9090:9090'
    networks:
      front_net:
      mgmt_net:
        aliases:
          - prometheus-dmz

  alertmanager:
    image: ${DOCKER_USERNAME}/alertmanager
    command:
      - '--config.file=/etc/alertmanager/config.yml'
    ports:
      - 9093:9093
    networks:
      mgmt_net:
        aliases:
          - alertmanager-dmz

volumes:
  grafana_data:

networks:
  front_net:
    external: true
  back_net:
    external: true
  mgmt_net:
    external: true
