groups:
  - name: alert.rules
    rules:
    - alert: InstanceDown
      expr: up == 0
      for: 1m
      labels:
        severity: page
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} has been down for more than 1 minute'
        summary: 'Instance {{ $labels.instance }} down'

    - alert: UIHTTPSlowAnswer
      expr: histogram_quantile(0.95, sum(rate(ui_request_latency_seconds_bucket[5m])) by (le)) > 0.03
      for: 1m
      #expr: sum(rate(ui_request_latency_seconds_bucket{job="ui"}[5m])) > 2
      annotations:
        description: '{{ $labels.instance }} of job {{ $labels.job }} takes long reponses'
        summary: 'HTTP response time of UI service is high'
